import Head from 'next/head'
import Dashboard from './page-components/organisms/dashboard'
import TopBar from './page-components/organisms/topbar';
import Footer from './page-components/organisms/footer';

export default function Home() {
  return (
    <>
      <div className="d-flex flex-column min-vh-100">
      <Head>
        <title>N-Cubotics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="d-flex flex-column h-100 flex-grow-1">
        <TopBar />
        <Dashboard />
        </main>
      <Footer />
    </div>
    </>
  );
}
