import Head from 'next/head'
import Dashboard from './page-components/organisms/dashboard'
import TopBar from './page-components/organisms/topbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>N-Cubotics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TopBar />
        <Dashboard />
      </main>
    </>
  );
}
